const suffixList = [
		["ager"],
		["balle"],
		["borg"],
		["bjerg"],
		//["bo"],
		["by"],
		["bølle", "bøl"],
		["dal", "dale"],
		["holt", "holte", "lt", "lte"],
		["høj", "høje", "øv", "øje", "ie"],
		["inge", "ing"],
		//["ker"],
		//["køb"],
		//["købing"],
		//["leje"],
		["lev"],
		["lund", "lunde"],
		//["løkke", "løk"],
		["løse", "lse"],
		["mark", "marke"],
		["næs", "nse", "ns"],
		["rud", "rød", "rod"],
		//["rum"],
		["skov"],
		["sted"],
		["tofte", "toft"],
		["torp", "rp"],
		["drup"],
		["trup"],
		["rup"],
		//["tved"],
		["um"],
		["vad"],
		["ved"],
		["ør", "øre", "er"]
			];

export default suffixList;
